### ISSUE TITLE
How many cores and RAM are needed for the `createDictionaries` process?

### ISSUE THREAD

**Issue by ctuni** [arthurvinx/Medusa#5]
Hello!

I'm trying to run this workflow on an AWS instance and it gets stuck on the aforementioned rule. I tried manually running the `createDictoonary.r` script without success. I tried running it on an instance with 32 CPUs and 96 GB of RAM to no avail. What are the hardware requirements for that script?

Thanks!

**Comment by jvfe** [comment]
If you're using the entire NCBI-nr database (as is the default), it can take from 180 to 210 GB of RAM. Memory is the main requirement, so if you have 6 or more CPUs available it should work.

**Comment by ctuni** [comment]
Understood! Thank you very much for the fast response
